update_buildconf: Fix typo causing a failure
Fix for:
    File ".../gen-machine-conf/lib/update_buildconf.py", line 89, in AddUserLayers
      common_utils.bitbake.shutdown()
    TypeError: bitbake.shutdown() missing 1 required positional argument: 'self'

Signed-off-by: Mark Hatle <mark.hatle@amd.com>
Acked-by: Raju Kumar Pothuraju <rajukumar.pothuraju@amd.com>