yocto_machine.py: Add BITSTREAM_PATH if bit file exists
If Zynq and ZynqMP design has only PS without PL, then gen-machineconf
will throw an error.

[WARNING] Unable to find a bit file in /scratch/sandeep/yocto/2024.2/yp-dev/build-sdt/hw-description/zc702-sdt, use the -p/--pl option to point to the directory containing a .bit file
Traceback (most recent call last):
  File "/wrk/yocto_dev/sandeep/github-int/yocto/Gen-Machine-Conf/gen-machineconf", line 219, in <module>
    ret = main()
  File "/wrk/yocto_dev/sandeep/github-int/yocto/Gen-Machine-Conf/gen-machineconf", line 213, in main
    ret = args.func(args)
  File "/wrk/yocto_dev/sandeep/github-int/yocto/Gen-Machine-Conf/lib/gen-machineconf/sdt_flow.py", line 848, in ParseSDT
    project_config.GenerateConfiguration(args, hw_info,
  File "/wrk/yocto_dev/sandeep/github-int/yocto/Gen-Machine-Conf/lib/project_config.py", line 293, in GenerateConfiguration
    machine_conf_file = yocto_machine.GenerateYoctoMachine(
  File "/wrk/yocto_dev/sandeep/github-int/yocto/Gen-Machine-Conf/lib/yocto_machine.py", line 600, in GenerateYoctoMachine
    machine_override_string += YoctoSdtConfigs(args, arch, dtg_machine,
  File "/wrk/yocto_dev/sandeep/github-int/yocto/Gen-Machine-Conf/lib/yocto_machine.py", line 484, in YoctoSdtConfigs
    args.pl = bit[0]
IndexError: list index out of range
[ERROR] list index out of range

Hence add BITSTREAM_PATH if bitstream file exits in sdtgen output
directory.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>

Acked-for-series: Mark Hatle <mark.hatle@amd.com>